# Generated by Django 3.1.3 on 2020-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_name', models.CharField(max_length=20)),
                ('provider_name', models.CharField(max_length=20)),
                ('revenue', models.IntegerField()),
                ('wons', models.IntegerField()),
                ('date_updated', models.DateField()),
                ('date_created', models.DateField()),
            ],
            options={
                'db_table': 'API_Data',
            },
        ),
    ]
